"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[opener]
edit = [
    { run = 'emacs "$@"', orphan = true, desc = "Emacs" },
]
view = [
    { run = 'nsxiv "$@"', orphan = true, desc = "nsxiv" },
]
play = [
    { run = 'mpv "$@"', orphan = true, desc = "mpv" },
]
browse = [
    { run = 'firefox "$@"', orphan = true, desc = "Firefox" },
]

[open]
prepend_rules = [
    { mime = "text/*",          use = "edit" },
    { mime = "image/*",         use = "view" },
    { mime = "video/*",         use = "play" },
    { mime = "audio/*",         use = "play" },
    { mime = "application/pdf", use = "edit" },
]
